vars:
  current_fedora: 36

repos:
  afterburn:
    url: https://github.com/coreos/afterburn
    vars:
      git_repo: afterburn
      crate: afterburn
      fedora_package: rust-afterburn
      rhel_package: rust-afterburn
      c9s_package: rust-afterburn

  butane:
    url: https://github.com/coreos/butane
    vars:
      git_repo: butane
      quay_repo: coreos/butane
      quay_legacy_repos: [coreos/fcct]
      fedora_package: butane
      rhel_package: butane
      macports_package: sysutils/butane

  coreos-installer:
    url: https://github.com/coreos/coreos-installer
    vars:
      git_repo: coreos-installer
      crate: coreos-installer
      quay_repo: coreos/coreos-installer
      fedora_package: rust-coreos-installer
      rhel_package: coreos-installer
      c9s_package: rust-coreos-installer

  fedora-coreos-streams:
    url: https://github.com/coreos/fedora-coreos-streams

  ignition:
    url: https://github.com/coreos/ignition
    vars:
      git_repo: ignition
      quay_repo: coreos/ignition-validate
      fedora_package: ignition
      rhel_package: ignition

  ignition-config-rs:
    url: https://github.com/coreos/ignition-config-rs
    vars:
      git_repo: ignition-config-rs
      crate: ignition-config
      fedora_package: rust-ignition-config

  openssh-keys:
    url: https://github.com/coreos/openssh-keys
    vars:
      git_repo: openssh-keys
      crate: openssh-keys
      fedora_package: rust-openssh-keys

  ssh-key-dir:
    url: https://github.com/coreos/ssh-key-dir
    vars:
      git_repo: ssh-key-dir
      crate: ssh-key-dir
      fedora_package: rust-ssh-key-dir
      c9s_package: rust-ssh-key-dir

  zincati:
    url: https://github.com/coreos/zincati
    vars:
      git_repo: zincati
      crate: zincati
      fedora_package: rust-zincati

templates:
  - fcos/release-checklist.md
  - go/release-checklist.md
  - rust/release-checklist.md
