vars:
  current_fedora: 36

repos:
  afterburn:
    url: https://github.com/coreos/afterburn
  butane:
    url: https://github.com/coreos/butane
  coreos-installer:
    url: https://github.com/coreos/coreos-installer
  fedora-coreos-streams:
    url: https://github.com/coreos/fedora-coreos-streams
  ignition:
    url: https://github.com/coreos/ignition
  ignition-config-rs:
    url: https://github.com/coreos/ignition-config-rs
  openssh-keys:
    url: https://github.com/coreos/openssh-keys
  ssh-key-dir:
    url: https://github.com/coreos/ssh-key-dir
  zincati:
    url: https://github.com/coreos/zincati

templates:
  - fcos/release-checklist.md
  - go/release-checklist.md
  - rust/release-checklist.md
