files:
  - repo: console-login-helper-messages
    path: .github/workflows/shellcheck.yml
    vars:
      branches:
        - main

  - repo: fedora-coreos-config
    path: .github/workflows/shellcheck.yml
    vars:
      branches:
        - testing-devel

  - repo: ignition
    path: .github/workflows/shellcheck.yml
    vars:
      branches:
        - main
