files:
  - repo: afterburn
    path: docs/_config.yml

  - repo: butane
    path: docs/_config.yml

  - repo: coreos-assembler
    path: docs/_config.yml

  - repo: coreos-installer
    path: docs/_config.yml

  - repo: ignition
    path: docs/_config.yml

  - repo: rpm-ostree
    path: docs/_config.yml

  - repo: zincati
    path: docs/_config.yml
